spring:
  application:
    name: SessionApplication
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # Pour avoir des sessions ind√©pendantes
  # Voir aussi SecurityConfig.cookieSerializer
#  session:
#    data:
#      redis:
#        namespace: SessionApplication

server:
  port: 8083
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
        secure: true
